[package]
name = "matrix_commands"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
matrix-sdk = { version = "0.7.1", features = ["markdown"] }
matrix_commands_macros={path="../matrix_commands_macros"}
serde_json = "1.0.117"
